<a href="https://colab.research.google.com/github/5556mani/AI-Engineering/blob/main/PyTorch/AutoGrad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# diffrentiation is difficult to write-- specially for the nested function
# nested is very important for deep learning

In [ ]:
import torch


In [ ]:
# create tensor and set requires grad to true
torch.manual_seed(42)  #---- have to be in the same cell
W=torch.rand((5,5),requires_grad=True)
W

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317, 0.1053]], requires_grad=True)

In [ ]:
X=W*100+1
# X.requires_grad_(True)  # this method changes you computation graph
                          # X will be new leaf and you can acces past grad
# to also acces the grad with X you should us X.retain_graf()
X.retain_grad()

In [ ]:
# create related variables ,we will see parameter that will show some backward relation for gradeint calculation , its computation graph
Y=X*2
Y

tensor([[178.4539, 185.0008,  78.5728, 193.8611,  80.0896],
        [122.1791,  53.3145, 160.7283, 190.1543,  28.6372],
        [188.9196, 120.7159, 175.8809, 115.5431, 150.2188],
        [ 87.8809, 179.0886, 116.7809,  55.3160, 127.4898],
        [ 55.9263,  90.2727,  61.3842, 168.3371,  23.0630]],
       grad_fn=<MulBackward0>)

In [ ]:
Z=Y.mean()
Z

tensor(119.5124, grad_fn=<MeanBackward0>)

In [ ]:
# .backward  to calculate grad and then .grad to show that value
Z.backward()

In [ ]:
X.grad

tensor([[0.0800, 0.0800, 0.0800, 0.0800, 0.0800],
        [0.0800, 0.0800, 0.0800, 0.0800, 0.0800],
        [0.0800, 0.0800, 0.0800, 0.0800, 0.0800],
        [0.0800, 0.0800, 0.0800, 0.0800, 0.0800],
        [0.0800, 0.0800, 0.0800, 0.0800, 0.0800]])

In [ ]:
W.grad

tensor([[8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.]])

In [ ]:
# clearing grad
# Z.backward() directly running this will throw error you have to make one forward pass as old computation graph is destroyed now
import torch
X=torch.tensor([1,2,3])
X=X.to(dtype=torch.float32)
X.requires_grad_(True)


tensor([1., 2., 3.], requires_grad=True)

In [ ]:
X.grad.zero_()
Z=(X**2).mean(dtype=float)
Z.backward()
X.grad


# if you run it multiple time values start geeting add
# to prevent this you need to call .grad.zero_()

tensor([0.6667, 1.3333, 2.0000])

In [ ]:
# to stop gradiect tracking
# --requires_grad_ , detach , no_grad

In [ ]:
import torch

X = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

# Toggle the tracking flag to False in-place
X.requires_grad_(False)

# Any operation downstream will NOT have a computation graph
Z = (X**2).mean()

print(Z.requires_grad)  # Output: False
# Z.backward()          # This will CRASH now because there is no graph

False


In [ ]:
import torch

X = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

# Create a severed view
X_detached = X.detach()

# The original X still tracks gradients, but X_detached does not
Y1 = (X**2).mean()          # Tracks gradients
Y2 = (X_detached**2).mean() # Does NOT track gradients

print("Original tracking:", Y1.requires_grad)  # Output: True
print("Detached tracking:", Y2.requires_grad)  # Output: False

Original tracking: True
Detached tracking: False


In [ ]:
import torch

X = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

# Everything inside this block has tracking suspended
with torch.no_grad():
    Y = X ** 2
    Z = Y.mean()
    print("Inside block tracking:", Z.requires_grad)  # Output: False

# As soon as you unindent, tracking turns back on automatically
Out = X * 2
print("Outside block tracking:", Out.requires_grad)  # Output: True

Inside block tracking: False
Outside block tracking: True
