<a href="https://colab.research.google.com/github/5556mani/AI-Engineering/blob/main/PyTorch/4_PyTorch_NN_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#nn modules have functionality to make layers , loss fnctions , and all other major components relate to construction and training of the moduke

In [ ]:
# key components

# Modules(layers)
# loss functions
# Contaniers
# Activation function
# Regularization

In [ ]:
# lets make a simple neural network


In [ ]:
# import torch and modules

In [ ]:
# create class
''' create class with inheritance from the nn.module
 construter with super constructer ,
 for simple use any layer type and activation function
 create forward function'''

' create class with inheritance from the nn.module\n construter with super constructer , \n for simple use any layer type and activation function\n create forward function'

In [ ]:
# create dummy data use model

In [ ]:
# use torchinfro summary for model info

In [ ]:
# lets make neural network with one hidden layer

In [ ]:
import torch.nn as nn
import torch

In [ ]:
#

In [ ]:
class One_hidden_NN(nn.Module):

  def __init__(self,input_shape):

    super().__init__()
    self.linear=nn.Linear(input_shape,3)
    self.relu=nn.ReLU()
    self.hidden=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self, features):

    out=self.linear(features)
    out=self.relu(out)
    out=self.hidden(out)
    out=self.sigmoid(out)

    return out


In [ ]:
dummy=torch.rand((5,7))

In [ ]:
model=One_hidden_NN(dummy.shape[1])

In [ ]:
dummy.dtype

torch.float32

In [ ]:
model(dummy)

tensor([[0.4878],
        [0.4920],
        [0.5031],
        [0.4867],
        [0.4946]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-2.9936e-01,  2.1514e-01,  3.0391e-04,  1.2353e-01,  3.0152e-02,
         -2.5480e-01, -1.1427e-01],
        [ 1.7429e-01,  9.6975e-02,  1.5732e-01,  1.9833e-01,  3.5778e-01,
          2.4941e-01, -1.9320e-01],
        [-7.3236e-02, -1.4835e-01, -1.9098e-01, -3.4788e-01, -3.6868e-01,
         -2.0568e-01, -4.0483e-02]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.0611, -0.3130,  0.1738], requires_grad=True)

In [ ]:
! pip install torchinfo

In [ ]:
from torchinfo import summary

In [ ]:
summary(model,input_size=dummy.shape)

Layer (type:depth-idx)                   Output Shape              Param #
One_hidden_NN                            [5, 1]                    --
├─Linear: 1-1                            [5, 3]                    24
├─ReLU: 1-2                              [5, 3]                    --
├─Linear: 1-3                            [5, 1]                    4
├─Sigmoid: 1-4                           [5, 1]                    --
Total params: 28
Trainable params: 28
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
# use container to reduce the codes

In [ ]:
class One_hidden_NN(nn.Module):

  def __init__(self,input_shape):

    super().__init__()
    self.seq=nn.Sequential(
                              nn.Linear(input_shape,3),
                              nn.ReLU(),
                              nn.Linear(3,1),
                              nn.Sigmoid()
                                                         )

  def forward(self, features):

    out=self.seq(features)

    return out


In [ ]:
# we built the neural network from the nn module
# we used built in activation function
# We used them in container

# two more thing to do
# use built in loss function and built in optimizer


In [ ]:
# call loss function, whereever you were calling the loss funxtion remove you self written loss function and replace that with this

In [ ]:
# similarly remove the manual updates of parameters and replace with torch.optim optimzzer.step , clear gradients with .zero_grad