<a href="https://colab.research.google.com/github/5556mani/AI-Engineering/blob/main/PyTorch/Basic_and_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# started at 9:36 AM 01/06/26

In [ ]:
# Pytorch Features
#   i)  Tensor Computations
#   ii) Dynamic computation graph
#   iii)GPU acceleration
#   iv) Interoperetability with other libraries
#   v)  Distribuited training
#   vi) Automatic diffrentiation

In [ ]:
# First video ended at 10:10

In [ ]:
# Second Video : Tensors in PyTorch , started in 10:12

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available:
  print("GPU is avaliable")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("Use CPU, sad life bro")

GPU is avaliable
Using GPU: Tesla T4


In [ ]:
# creating tensor

In [ ]:
# around 10:39 i talked to lovely

In [ ]:
# different methods to create tensor:
'''
empty   , can chedk type, ndim, shape
zeros
ones
rand
manual_seed
tensor   anything list,tuple

arange
linspace
eye
full

'''

'\nempty   , can chedk type, ndim, shape\nzeros\nones\nrand\nmanual_seed\ntensor   anything list,tuple\n\narange\nlinspace\neye\nfull\n\n'

In [ ]:
a=torch.empty((2,2))
print(a)
a.shape

tensor([[2.3742e-30, 4.4580e-41],
        [4.1035e+01, 0.0000e+00]])


torch.Size([2, 2])

In [ ]:
a=torch.zeros(size=(2,3))
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
a=torch.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.8903, 0.0050, 0.5636],
        [0.6659, 0.0628, 0.1427]])

In [ ]:
manual_seed=42
size=[]
a=torch.rand(2,3)
a

tensor([[0.1975, 0.0243, 0.4903],
        [0.0869, 0.3240, 0.8558]])

In [ ]:
a=torch.tensor([[1,2],[2,3]])
a

tensor([[1, 2],
        [2, 3]])

In [ ]:
a=torch.tensor([[1,2],[2,3]])
a

tensor([[1, 2],
        [2, 3]])

In [ ]:
'''
arange
linspace
eye
full

'''

In [ ]:
a=torch.arange(1,10,3)
a

tensor([1, 4, 7])

In [ ]:
a=torch.linspace(0,9,4)
a

tensor([0., 3., 6., 9.])

In [ ]:
a=torch.eye(7,6) #nice
a

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.]])

In [ ]:
a=torch.full(fill_value=5,size=(3,3))
a

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [ ]:
# to find the shape
'''

.shape
.empty_like
.zeros_like
.ones_like
.rand_like   -- it will give error becasue rand_like generate floats and may be entry in ( ) is not float type

'''

'\n\n.shape\n.empty_like\n.zeros_like\n.ones_like\n.rand_like   -- it will give error becasue rand_like generate floats and may be entry in ( ) is not float type\n\n'

In [ ]:
a.shape

torch.Size([3, 3])

In [ ]:
b=torch.empty_like(a)
b
# all other are almost same

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 1]])

In [ ]:
# data type
'''

.dtype---- check data type and create with speific datatype
.to --- to change the data type with dtype in ( ) to change dtype if we put device there it will change device type like from GPU to CPU


In [ ]:
print(a.dtype)
a=a.to(dtype=torch.float32)   # this is not inplace changer
print(a.dtype)

torch.int64
torch.float32


In [ ]:
# Mathematical operations on Tensor

# Scalar operation--jsut do it man , it will be element wise
# element wise operation---- do operation between two tensor it will be element wise
# single tensor operation---- abs,neg,round,ceil,floor,clamp
# Reduction operation -------sum,sum-can be specified with dimension,mean-same as sum-need dtype=float or complex-not long,median,max,min,product,standard-deviation,var,argmax/min. check how arg is giving the output
# Matrix operations--------.matmul(f,g),Transpose,detereminant,inverse,dot
# comparision--------------- simply use <,>,==,!=
# special function-----------.log,.exp,.sqrt, .sigmoid dimension wiese, .relu
# inplace operation---------  .add_, .relu_,


In [ ]:
a=torch.tensor([[-1,0.1],[2,3]])

In [ ]:
a*2  # similarly all other /,+,-,//,%

tensor([[-2.0000,  0.2000],
        [ 4.0000,  6.0000]])

In [ ]:
a

tensor([[-1.0000,  0.1000],
        [ 2.0000,  3.0000]])

In [ ]:
# if previous signs used between two tennsors then it will perform element wise operation

In [ ]:
a.abs()

tensor([[1.0000, 0.1000],
        [2.0000, 3.0000]])

In [ ]:
a.clamp(4)

tensor([[4., 4.],
        [4., 4.]])

In [ ]:
# Reduction operation -------sum,sum-can be specified with dimension,mean-same as sum-need dtype=float or complex-not long,median,max,min,product,standard-deviation,var,argmax/min. check how arg is giving the output
# Matrix operations--------.matmul(f,g),Transpose,detereminant,inverse,dot
# comparision--------------- simply use <,>,==,!=
# special function-----------.log,.exp,.sqrt, .sigmoid dimension wiese, .relu
# inplace operation---------  .add_, .relu_,


In [ ]:
a.argmin()

tensor(0)

In [ ]:
b=torch.randint_like(a,1,4)
b

tensor([[2., 3.],
        [2., 3.]])

In [ ]:
product=a.matmul(b)
product

tensor([[-1.8000, -2.7000],
        [10.0000, 15.0000]])

In [ ]:
a

tensor([[-1.0000,  0.1000],
        [ 2.0000,  3.0000]])

In [ ]:
T=a.transpose(0,1)   # it will swap these two dimension
T

tensor([[-1.0000,  2.0000],
        [ 0.1000,  3.0000]])

In [ ]:
I=a.inverse()
I

tensor([[-0.9375,  0.0312],
        [ 0.6250,  0.3125]])

In [ ]:
E=I.matmul(a)

In [ ]:
I>a

tensor([[ True, False],
        [False, False]])

In [ ]:
E.log()

tensor([[0., -inf],
        [-inf, 0.]])

In [ ]:
# Copying a tensor

'''
b = a # but this copy is not created by value it is created by referece , but in normal python those copy are copied by value just to let you know
      # id of a and b will be same
to avoid this we will use .clone()

'''


In [ ]:
a.add_(E)

tensor([[0.0000, 0.1000],
        [2.0000, 4.0000]])

In [ ]:
# Tensors Operations on GPU

In [ ]:
import torch
torch.cuda.is_available()


True

In [ ]:
device=torch.device('cuda')

In [ ]:
# creating tensor in GPU
# same as all previous, just add device='cuda' in parameter
# or we can move already created tensors to GPU by a.to(device)  a is old tensor

In [ ]:
ag = torch.randint(0, 10, (2, 3), device=device)

print("Tensor ag:\n", ag)
print("\nShape:", ag.shape)
print("Device:", ag.device)
print("Device :", a.device)
a=a.to(device)   # no inplace mdoificatiion just variable assigned to gpu location
print("\nMoved to device:\n",) # to is also used to change dtype and it is out of place operation
print("\nDevice ", b.device)

Tensor ag:
 tensor([[4, 1, 7],
        [3, 5, 9]], device='cuda:0')

Shape: torch.Size([2, 3])
Device: cuda:0
Device : cuda:0

Moved to device:


Device  cuda:0


In [ ]:
# Reshape tensors

'''
.reshape #in this make sure total number if elements remain same
.flatten # convert everything to 1d
.permute(j,k,i) change the index of dimension
,unsqueeze
.squeeze

'''

'\n.reshape #in this make sure total number if elements remain same\n.flatten # convert everything to 1d\n.permute(j,k,i) change the index of dimension \n,unsqueeze\n.squeeze\n\n'

In [ ]:
import torch

# Start with a simple 1D tensor (like a basic list)
x = torch.tensor([5, 6, 7])
print("Original x:")
print(x)
print("Shape:", x.shape)  # Output: torch.Size([3])
print("-" * 30)

# ==========================================
# 1. UNSQUEEZE: Adding a dimension
# ==========================================

# Let's add a dimension at index 0 (the very front)
# This turns our 1D array into a 2D matrix with 1 row and 3 columns.
x_unsqueezed_0 = x.unsqueeze(dim=0)
print("\nUnsqueeze at dim=0:")
print(x_unsqueezed_0)
print("Shape:", x_unsqueezed_0.shape)  # Output: torch.Size([1, 3])

# What if we add a dimension at index 1 instead?
# This turns it into a 2D matrix with 3 rows and 1 column (a column vector).
x_unsqueezed_1 = x.unsqueeze(dim=1)
print("\nUnsqueeze at dim=1:")
print(x_unsqueezed_1)
print("Shape:", x_unsqueezed_1.shape)  # Output: torch.Size([3, 1])
print("-" * 30)

# ==========================================
# 2. SQUEEZE: Removing a dimension
# ==========================================

# Let's take that [1, 3] tensor and squish it back down!
# If you don't pass a dimension, .squeeze() looks for ANY dimension
# of size 1 and removes it.
x_squeezed = x_unsqueezed_0.squeeze()
print("\nSqueeze (removes the '1'):")
print(x_squeezed)
print("Shape:", x_squeezed.shape)  # Output: torch.Size([3])

# Note: .squeeze() ONLY removes dimensions that are exactly size 1.
# If you try to squeeze a tensor with shape [2, 3], nothing happens!

Original x:
tensor([5, 6, 7])
Shape: torch.Size([3])
------------------------------

Unsqueeze at dim=0:
tensor([[5, 6, 7]])
Shape: torch.Size([1, 3])

Unsqueeze at dim=1:
tensor([[5],
        [6],
        [7]])
Shape: torch.Size([3, 1])
------------------------------

Squeeze (removes the '1'):
tensor([5, 6, 7])
Shape: torch.Size([3])


In [ ]:
# NumPy and PyTorch
import numpy as np

In [ ]:
# b=a.numpy ( ) will convert tensor a to numpy array b
# a=torch.from_numpy(b) to covert in tensor from numpy